### ISSUE TITLE
[QUESTION] Chunks possibly not loading

### ISSUE THREAD

**Issue by zmspiler** [Trivernis/spigot-chunkmaster#51]
**Question**

Hey there! I'd like to ask about dynmap integration with chunkmaster.

I have a world that is currently 15k * 15k blocks in size. After leaving chunkmaster to generate most of that area, a lot of it still didn't show on dynmap.

I'm thinking of a few issues that could be the problem:
* Dynmap rendering way slower (I have read that it is but it doesn't really make sense to me why it would generate such a shattered map)
* Method not always being called?
* I'm using a custom world generator
* I have to do `/dynmap fullrender` (tried before on a 1000 * 1000 area, didn't work)

take this with a grain of salt, I am by no means an expert on how chunks are generated, in fact, I don't know how it's done.

**Additional context**

config.yml
```yaml
generation:
  period: 1
  chunks-per-step: 60
  chunk-skips-per-step: 100
  mspt-pause-threshold: 500
  pause-on-join: false
  max-pending-chunks: 200
  max-loaded-chunks: 1000
  ignore-worldborder: false
database:
  filename: chunkmaster.db
language: en
dynmap: true
```

Screenshot of dynmap
https://i.imgur.com/jBaMKdM.jpg

Server specs
CPU: Ryzen 5 3600
RAM 64GB (mc server has 16G assigned)
DISK: 512 NVMe

Running spigot 1.15.2

Thank you in advance and kind regards,
Querrin
